name: Feature request
description: Πρόσθεσε νέα δυνατότητα
labels: ["type:feature"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Σύνοψη
      description: Σύντομη περιγραφή της δυνατότητας
    validations:
      required: true
  - type: textarea
    id: value
    attributes:
      label: Λόγος/Value
    validations:
      required: true
  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance Criteria
      options:
        - label: Κριτήριο 1
        - label: Κριτήριο 2
