name: Add new issues to Codex Project
on:
  issues:
    types: [opened]
permissions:
  issues: write
  contents: read
jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        with:
          gh_token: ${{ secrets.PROJECTS_TOKEN }}
          organization: Culturekey413
          project_id: 2
          resource_node_id: ${{ github.event.issue.node_id }}
          
