name: Add new issues to Codex Project
on:
  issues:
    types: [opened]
permissions:
  issues: write
  contents: read
jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1
        with:
          
          project-url: https://github.com/users/Culturekey413/projects/2
          github-token: ${{ secrets.PROJECTS_TOKEN }}
