name: auto-request-review

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Request review (safe mode)
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            if (!number) {
              console.log("ℹ️ No pull request context found — skipping auto-review request.");
              return;
            }

            await github.rest.pulls.requestReviewers({
              owner,
              repo,
              pull_number: number,
              reviewers: ['Culturekey413']
            });

            // Optional log for pulse tracking
            console.log(`✅ Auto-review requested by ${owner}/${repo} for PR #${number}`);
