name: Auto triage
on:
  issues:
    types: [opened, edited]
permissions:
  issues: write
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const hasType = issue.labels.some(l => l.name && l.name.startsWith('type:'));
            const toAdd = [];
            if (!hasType) toAdd.push('type:docs');
            if (!issue.labels.some(l => l.name && l.name.startsWith('prio:'))) toAdd.push('prio:P2');
            if (!issue.labels.some(l => l.name && l.name.startsWith('status:'))) toAdd.push('status:ready');
            if (toAdd.length) {
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number: issue.number,
                labels: toAdd
              });
            }
