name: auto-request-review
on:
  push:
    branches:
      - main
      - agent-toolkit
  pull_request:
    branches:
      - main
      - agent-toolkit
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            await github.rest.pulls.requestReviewers({
              owner,
              repo,
              pull_number: number,
              reviewers: ['@Culturekey413']
            });

