name: Insight Tracker v1 (Ethical)

on:
  schedule:
    - cron: "0 9 * * MON"   # κάθε Δευτέρα 09:00 UTC
  workflow_dispatch:        # να μπορείς να το τρέχεις και χειροκίνητα

permissions:
  contents: write           # για commit στο repo

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Collect traffic & append to metrics log
        env:
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.INSIGHTS_TOKEN }}
        run: |
          mkdir -p metrics
          TODAY=$(date -u +"%Y-%m-%d")

          # Τραβάμε τα 14-day traffic stats (views & clones)
          VIEWS_JSON=$(gh api repos/$REPO/traffic/views)
          CLONES_JSON=$(gh api repos/$REPO/traffic/clones)

          # Repo counters για context
          REPO_JSON=$(gh api repos/$REPO)

          VIEWS_TOT=$(echo "$VIEWS_JSON" | jq '.count')
          VIEWS_UNIQ=$(echo "$VIEWS_JSON" | jq '.uniques')
          CLONES_TOT=$(echo "$CLONES_JSON" | jq '.count')
          CLONES_UNIQ=$(echo "$CLONES_JSON" | jq '.uniques')

          STARS=$(echo "$REPO_JSON" | jq '.stargazers_count')
          FORKS=$(echo "$REPO_JSON" | jq '.forks_count')
          OPEN_ISSUES=$(echo "$REPO_JSON" | jq '.open_issues_count')

          {
            echo "## $TODAY"
            echo "- Views (14d): **$VIEWS_TOT**  _(unique: $VIEWS_UNIQ)_"
            echo "- Clones (14d): **$CLONES_TOT**  _(unique: $CLONES_UNIQ)_"
            echo "- Stars: **$STARS** • Forks: **$FORKS** • Open issues: **$OPEN_ISSUES**"
            echo ""
          } >> metrics/INSIGHTS_LOG.md

      - name: Commit metrics (if changed)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add metrics/INSIGHTS_LOG.md
            git commit -m "chore(metrics): weekly insights $(date -u +%Y-%m-%d)"
            git push
          else
            echo "No changes to commit."
          fi
