name: Rhime — Truth Detection Checks

on:
  push:
    branches:
      - main
      - agent-toolkit
    paths:
      - 'modules/Rhime/**'
      - 'core/**'
      - '.github/workflows/truth_detection.yml'
  pull_request:
    branches:
      - main
      - agent-toolkit
    paths:
      - 'modules/Rhime/**'
      - 'core/**'
      - '.github/workflows/truth_detection.yml'
  schedule:
    - cron: '0 6 * * 1'  # Δευτέρα 06:00 UTC
  workflow_dispatch:

concurrency:
  group: rhime-checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rhime-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Rhime Truth Flow
        run: bash .github/scripts/check_truth_pulse.sh
